/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  promptSidebar: [
    {
      type: 'autogenerated',
      dirName: 'prompts',   // ← folder inside docs-site/docs/
    },
  ],
};
